### PR TITLE
make didInsertNode promise aware. fixes #57

### LINKED ISSUE #57: Advice for dealing with ansync setup in parent components?
I'm curious if there's any general advice for how to deal with async methods when using this addon. The setup process of my parent component takes some time, and then the `didInsertParent` of the child component is called before the parent component is fully ready. Is there a standard way of synchronizing everything?

I think that covers the general question, but just in case more details would be helpful here are some more.

This is the general structure that I'm going for.

```
<BouncePlayer::Wavesurfer @bounce={{@bounce}} as |wavesurfer|>
  <wavesurfer.regions as |regions|>
    <regions.marker @start={{this.start}} @end={{this.end}}/>
  </wavesurfer.regions>
</BouncePlayer::Wavesurfer::Display>
``` 

In the `Regions` component the `didInsertParent` method looks like this:

```javascript
  @action
  async didInsertParent(element) {
    this.regions = await RegionsPlugin.create({});
    await this.args.wavesurfer.registerPlugin(this.regions); 
  }
```

Sometimes this works great, but sometimes it fails with an error saying `Uncaught TypeError: Cannot read properties of null (reading 'registerPlugin')` due to the `wavesurfer` object that is passed in from the parent not being full initialized yet.

Is there a standard way of dealing with this sort of situation?

### PR DESCRIPTION
**Pull request by miguelcobain**
@jagthedrummer this version seems to pass the tests

Changes from your PR:
- this uses `Promise.all` on all the children's `didInsertNode` calls. Your version was basically not doing any waiting since you were calling forEach, which isn't promise aware.
- this moves `this._didSetup = true;` to the top of the `setup` function which is important for the timing of the `registerChild` which calls `setup`

Can you try this on your codebase?

I would love to add tests for this, but I didn't find a good way to test execution order with promises. 😞 
I'm also considering if it makes sense to make `willDestroyParent` promise aware.

### CODE REVIEW

**Comment by jagthedrummer** [comment]
@miguelcobain, this is working great for me! When using my branch I had noticed that the children would fire `didInsertParent` twice, but I had thought it was due to some weirdness in my app code around async relationships and that the children were actually getting added to the DOM twice. Looks like it was probably due to the placement of `this._didSetup = true;`.

Anyway, this works great in my project. Seems like making `willDestroyParent` also be promise aware might not hurt.

Thanks for this!

**Comment by jagthedrummer** [comment]
Oh, I should also mention that I'm able to run tests locally now on this branch.

**Comment by miguelcobain** [comment]
@jagthedrummer I added some tests. QUnit's `assert.step` proved to be a much simpler way to test things than sinon. Unfortunately, there's a failing test for the async scenario.
Still trying to understand if the problem is the promise-aware implementation or the tests themselves for async.

Failing test is `didInsertParent hook runs in the correct order (async): top-level parent and two children-parents after if`

**Comment by miguelcobain** [comment]
@jagthedrummer I refactored the project. It should be working now. Both `didInsertParent` and `willDestroyParent` are promise-aware, and it's all tested!

Can you test if this works on your codebase?

**Comment by jagthedrummer** [comment]
After switching to this branch I'm getting an error which seems to be preventing `didInsertParent` from firing in my child components.

```
Uncaught (in promise) TypeError: fn is not a function
    at Object.installModifier (did-insert.js:62:1)
```

CleanShot 2024-03-08 at 09 59 12

And this is the bit of code that the first line of the stack trace points to:

CleanShot 2024-03-08 at 10 04 55

It seems like `ember/render-modifiers` thinks that the function to call on `did-insert` isn't being passed in.

**Comment by miguelcobain** [comment]
This is weird. Are you 100% sure it comes from ember-composability-tools?
The only place we're using the modifier is `{{did-insert this.setup}}`, and `this.setup` definitely exists.

**Comment by jagthedrummer** [comment]
OK, after studying all the changes in this PR I see that it's due to this PR introducing a breaking change.

I'm extending `Root` and `Node` and I had to change the template for my `Root` component.

I had to change this:

```handlebars
<div
  {{did-insert this.didInsertNode}}
  {{will-destroy this.willDestroyNode}}
>
  ...
</div>
```

To this:

```handlebars
<div
  {{did-insert this.setup}}
>
  ...
</div>
```

Fwiw, this is related to the fact that I'm still extremely unclear on whether the intended use for `ect` is to _extend_ `Root` & `Node` or to just use them directly. The `README` says to extend them, but doesn't provide a complete example. And the info in the `README` seems to contradict the advice you gave in [this comment](https://github.com/miguelcobain/ember-composability-tools/issues/56#issuecomment-1741240529). Maybe both approaches are valid depending on what you're trying to do? It would be super helpful to get some clarification on that point.

But confusion aside, once I updated my project to account for the breaking change everything seems to be working fine.

**Comment by miguelcobain** [comment]
@jagthedrummer I see. I think I should fix that story. The problem with extending Root or Node is that the template gets overriden, which is an important part of how the whole system works.

I think the best way at the moment is to use Root and Node directly in your own components. Definitely the "safest" way.
The only downside I see is having access to `this.children`. We could yield the children, but you would have to somehow propagate that to your component's js.

If you don't need `this.children`, then using the Root and Node components directly in your own components is the best way for sure.

**Comment by jagthedrummer** [comment]
Is there anything I can do to help get this landed and released?

**Comment by miguelcobain** [comment]
@jagthedrummer version `1.3.0` was published

**Comment by jagthedrummer** [comment]
Thanks a bunch, @miguelcobain! And thanks again for this excellent addon. I owe you a few beverages if there's ever the opportunity. Cheers!

**Pull request merged**
